"""
Django settings for csr project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qt5y!#6+c(lahhy0q%ulzm-_b(mf2b%ii$noc!m#%nwzb8&6#@'
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'qt5y!#6+c(lahhy0q%ulzm-_b(mf2b%ii$noc!m#%nwzb8&6#@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = os.environ.get('DJANGO_DEBUG', '') != False

ALLOWED_HOSTS = ['*']

AWS_ACCESS_KEY_ID = 'AKIAJ6XXDC6JP6YFPBVQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_REGION = 'ap-southeast-1'

# Generated by using cryptography module
CRYPT_KEY = "EYuHD5qgQg9tdw-Pc88v3yK0myk17UmylIJ0dq-S6XM="


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'import_export',
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.If_Session_Idle_Timeout'
]

ROOT_URLCONF = 'csr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'core/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'csr.wsgi.application'


AUTH_USER_MODEL = 'core.User'



# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'csr',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

SESSION_TIMEOUT = 60*15
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

IMPORT_EXPORT_USE_TRANSACTIONS = False

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 102400
DATA_UPLOAD_MAX_MEMORY_SIZE = 100000000


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

#for static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]


#for media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# for logging
PROJECT_NAME = BASE_DIR.split('\\')[-1]
LOG_FILES = ['csr','csr_except']
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        LOG_FILES[0]+'_log': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename' : BASE_DIR+'\\'+'media'+'\\logs\\'+LOG_FILES[0]+'.log',
            'formatter': 'verbose',
            'filters': ['require_debug_true']
        },
    'PP_'+LOG_FILES[0]+'_log': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename' : BASE_DIR+'\\'+'media'+'\\logs\\'+LOG_FILES[0]+'.log',
            'formatter': 'verbose', 
            'filters': ['require_debug_false'],
        },
        LOG_FILES[1]+'_log': {
            'level': 'CRITICAL',
            'class': 'logging.FileHandler',
            'filename' : BASE_DIR+'\\'+'media'+'\\logs\\'+LOG_FILES[1]+'.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        LOG_FILES[0]: {
            'handlers': [LOG_FILES[0]+'_log','PP_'+LOG_FILES[0]+'_log'],
            'level': 'DEBUG',
            'propagate': True,
        },
        LOG_FILES[1]: {
            'handlers': [LOG_FILES[1]+'_log'],
            'level': 'DEBUG',
            'propagate': True,
        },
    
    },
}